app:
    resource: "@AppBundle/Controller/"
    type:     annotation

display_product:
    path: /product/{id}
    defaults:
        _controller: AppBundle:Default:displayProduct
do_payment:
    path: /do/payment
    defaults:
        _controller: AppBundle:Default:doPayment

confirm_payment:
    path: /confirm/payment
    defaults:
        _controller: AppBundle:Default:confirmPayment

my_name:
    path: /name/kuba
    defaults:
        _controller: AppBundle:Default:index

it_works:
    path: /it/it_works
    defaults:
        _controller: AppBundle:Default:myName

read_book:
    path: /book/read/{title}
    defaults:
        _controller: AppBundle:Default:readBook
        page: 1