app:
    resource: "@AppBundle/Controller/"
    type:     annotation

my_name:
    path: /name/kuba
    defaults:
        _controller: AppBundle:Default:index

it_works:
    path: /it/it_works
    defaults:
        _controller: AppBundle:Default:myName

read_book:
    path: /book/read/{title}
    defaults:
        _controller: AppBundle:Default:readBook
        page: 1